export const products = [
  {
    id: 1,
    name: "کیک تولد",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/birthday-cake/1.jpg",
  },
  {
    id: 2,
    name: "کیک تولد",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/birthday-cake/2.jpg",
  },
  {
    id: 3,
    name: "کیک تولد",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/birthday-cake/3.jpg",
  },
  {
    id: 4,
    name: "کیک تولد",
    filling: ["موز", "گردو", "گیلاس"],
    price: 500_000,
    imageUrl: "/public/images/products/birthday-cake/4.jpg",
  },
  {
    id: 5,
    name: "کوکی",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/cookie/1.jpg",
  },
  {
    id: 6,
    name: "کوکی",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/cookie/2.jpg",
  },
  {
    id: 7,
    name: "کوکی",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/cookie/3.jpg",
  },
  {
    id: 8,
    name: "شیرینی تر",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/creamy-pastry/1.jpg",
  },
  {
    id: 9,
    name: "شیرینی تر",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/creamy-pastry/2.jpg",
  },
  {
    id: 10,
    name: "شیرینی تر",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/creamy-pastry/3.jpg",
  },
  {
    id: 11,
    name: "شیرینی خشک",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/dry-sweets/1.jpg",
  },
  {
    id: 12,
    name: "شیرینی خشک",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/dry-sweets/2.jpg",
  },
  {
    id: 13,
    name: "شیرینی خشک",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/dry-sweets/3.jpg",
  },
  {
    id: 14,
    name: "کیک عصرانه",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/evening-cake/1.jpg",
  },
  {
    id: 15,
    name: "کیک عصرانه",
    filling: ["موز", "گردو", "توت فرنگی"],
    price: 500_000,
    imageUrl: "/public/images/products/evening-cake/2.jpg",
  },
  {
    id: 16,
    name: "کیک عصرانه",
    filling: ["موز", "گردو"],
    price: 500_000,
    imageUrl: "/public/images/products/evening-cake/3.jpg",
  },
];
